"""End-to-end smoke test simulating a new user's first deck build.

Steps:
  1. Build a minimal 3-slide narrative (cover + content + closing CTA)
  2. Run brief-time QC (twins.brief_qc.check_brief)
  3. Derive briefs + propose 3 options per slide (selector)
  4. Pick top option per slide
  5. Compose deck on a reference client template (composer)
  6. Run render-time QC on each composed slide (twins.render_qc)
  7. Report success/failure + paths

This is the path a fresh-clone user would invoke. Any breakage here is
a real shipability issue.
"""
import sys
import traceback
from pathlib import Path

# Path setup — same as a new user would do
SKILLS_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(SKILLS_ROOT / "slide-builder"))

CLIENT_TEMPLATE = str(SKILLS_ROOT / "references" / "PPT Files" / "09_Cover Divider.pptx")
OUT_DIR = SKILLS_ROOT / "_smoke_out"
OUT_DIR.mkdir(exist_ok=True)
OUT_PPTX = str(OUT_DIR / "smoke-test-deck.pptx")


NARRATIVE = [
    {
        "slide_num": 1,
        "governing_thought": "[Cover slide]",
        "editorial_emphasis": "Title, tagline, presenter only.",
        "content": {
            "cover": {
                "title": "Smoke Test Deck",
                "tagline": "Verifying the Slide Lab pipeline end-to-end.",
                "subtitle": "Auto-generated by _smoke_e2e.py to confirm a new user can build a deck after cloning.",
                "presenter": "Slide Lab Smoke Test",
                "date": "2026-05-20",
                "audience": "Reviewer",
                "eyebrow": "AUDIT VALIDATION",
            }
        },
    },
    {
        "slide_num": 2,
        "governing_thought": "Three failure modes consultants hit when cutting through analysis.",
        "so_what": "The fix is structural, not personal — give people a way to think, argue, and build.",
        "editorial_emphasis": "Three peer-level causes rolled to one conclusion.",
        "content": {
            "cards": [
                {"heading": "Too much to say", "body": "Volume of analysis grows faster than the bandwidth of any single deck can carry."},
                {"heading": "Too many cooks", "body": "Every collaborator has a view; more opinions mean harder choices, not richer arguments."},
                {"heading": "Buried recommendations", "body": "The audience needs the next step; most decks bury it under context."},
            ],
        },
    },
    {
        "slide_num": 3,
        "governing_thought": "Try one real deck — if it lands, pass it on.",
        "so_what": "The door is open. Walk through it.",
        "editorial_emphasis": "the ask",
        "content": {
            "primary_ask": "Run Slide Lab on your next steering committee deck.",
            "sub_asks": [
                {"label": "Install", "body": "Clone the repo and pip install -r requirements.txt."},
                {"label": "Try", "body": "Build one real deck — your next status update is enough."},
                {"label": "Share", "body": "If it lands, send the link to one teammate."},
            ],
        },
    },
]


def step(n, label):
    print(f"\n[{n}] {label}")
    print("-" * (len(label) + 4))


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    print("=" * 70)
    print("Slide Lab E2E Smoke Test")
    print("=" * 70)
    print(f"Skills root:       {SKILLS_ROOT}")
    print(f"Client template:   {CLIENT_TEMPLATE}")
    print(f"  exists:          {Path(CLIENT_TEMPLATE).exists()}")
    print(f"Output PPTX:       {OUT_PPTX}")
    failures = []

    # Step 1: imports
    step(1, "Import twins modules")
    try:
        from twins.selector import load_catalog, propose_options
        from twins.build_with_options import prepare_deck_specs, compose_picked_deck
        from twins.brief_qc import check_brief
        from twins.render_qc import check_composed_pptx
        from twins.overrides_resolver import pattern_aware_overrides
        from twins.review_html import narrative_slide_to_overrides
        print("  OK")
    except Exception as e:
        print(f"  FAIL: {type(e).__name__}: {e}")
        failures.append(("import", e))
        return failures

    # Step 2: brief-time QC
    step(2, "Brief-time QC (check_brief)")
    try:
        qc = check_brief(NARRATIVE)
        print(f"  {qc['summary']}")
        for b in qc["blocking"]:
            print(f"  ! BLOCKING: {b}")
        for w in qc["warnings"][:5]:
            print(f"  ~ warning: {w}")
        if len(qc["warnings"]) > 5:
            print(f"  ... +{len(qc['warnings']) - 5} more warnings")
    except Exception as e:
        print(f"  FAIL: {type(e).__name__}: {e}")
        failures.append(("brief_qc", e))

    # Step 3: load catalog
    step(3, "Load catalog")
    try:
        catalog = load_catalog()
        print(f"  {len(catalog)} patterns loaded")
    except Exception as e:
        print(f"  FAIL: {type(e).__name__}: {e}")
        failures.append(("load_catalog", e))
        return failures

    # Step 4: prepare deck specs (derive brief + propose options per slide)
    step(4, "Derive briefs + propose options per slide")
    try:
        specs = prepare_deck_specs(NARRATIVE, top_n=3, deck_type="capability-pitch")
        for s in specs:
            print(f"  slide {s['slide_num']}: {len(s['options'])} options")
            for o in s["options"]:
                e = o["entry"]
                print(f"    [{o['score']:>3}] {o['pattern']} | {e.get('family')}/{e.get('layout')}")
    except Exception as e:
        print(f"  FAIL: {type(e).__name__}: {e}")
        traceback.print_exc()
        failures.append(("prepare_deck_specs", e))
        return failures

    # Step 5: pick top option per slide + collect overrides
    step(5, "Pick top option per slide + map narrative -> overrides")
    picks = []
    try:
        for s in specs:
            if not s["options"]:
                print(f"  slide {s['slide_num']}: no options! skipping")
                continue
            top = s["options"][0]
            narrative_slide = next(n for n in NARRATIVE if n["slide_num"] == s["slide_num"])
            pattern_entry = top.get("entry") or {}
            if pattern_entry.get("shape_role_map"):
                overrides = pattern_aware_overrides(narrative_slide, pattern_entry)
                source = "pattern-aware"
            else:
                overrides = narrative_slide_to_overrides(narrative_slide)
                source = "fan-out (legacy)"
            picks.append({"pattern": top["pattern"], "overrides": overrides})
            print(f"  slide {s['slide_num']}: picked {top['pattern']} with {len(overrides)} overrides ({source})")
    except Exception as e:
        print(f"  FAIL: {type(e).__name__}: {e}")
        traceback.print_exc()
        failures.append(("pick_options", e))
        return failures

    # Step 6: compose deck
    step(6, "Compose deck (compose_picked_deck)")
    if not Path(CLIENT_TEMPLATE).exists():
        print(f"  SKIP: client template missing at {CLIENT_TEMPLATE}")
        failures.append(("compose_picked_deck", FileNotFoundError(CLIENT_TEMPLATE)))
    else:
        try:
            out_path = compose_picked_deck(
                picks=picks,
                out_path=OUT_PPTX,
                client_template=CLIENT_TEMPLATE,
                verbose=False,
            )
            print(f"  OK: {out_path}")
            print(f"  size: {Path(out_path).stat().st_size:,} bytes")
        except Exception as e:
            print(f"  FAIL: {type(e).__name__}: {e}")
            traceback.print_exc()
            failures.append(("compose_picked_deck", e))

    # Step 7: render-time QC per slide
    step(7, "Render-time QC (check_composed_pptx)")
    if not Path(OUT_PPTX).exists():
        print("  SKIP: no output PPTX to inspect")
    else:
        try:
            verdict = check_composed_pptx(OUT_PPTX)
            print(f"  verdict: {verdict['verdict']}")
            for issue in verdict["issues"][:8]:
                print(f"  [{issue['severity']}] {issue['msg']}")
            if len(verdict["issues"]) > 8:
                print(f"  ... +{len(verdict['issues']) - 8} more issues")
        except Exception as e:
            print(f"  FAIL: {type(e).__name__}: {e}")
            traceback.print_exc()
            failures.append(("render_qc", e))

    # Step 8: LibreOffice render to PNG (the silent path)
    step(8, "PPTX -> PNG via LibreOffice (slide-qc render_libre)")
    if not Path(OUT_PPTX).exists():
        print("  SKIP: no PPTX to render")
    else:
        try:
            sys.path.insert(0, str(SKILLS_ROOT / "slide-qc" / "scripts"))
            from render_slides import render_libre
            png_out = OUT_DIR / "pngs"
            render_libre(Path(OUT_PPTX), png_out, dpi=100)
            pngs = sorted(png_out.glob("slide_*.png"))
            print(f"  rendered {len(pngs)} PNG(s)")
            for p in pngs:
                print(f"    {p.name} ({p.stat().st_size:,} bytes)")
        except Exception as e:
            print(f"  FAIL: {type(e).__name__}: {e}")
            traceback.print_exc()
            failures.append(("render_libre", e))

    return failures


if __name__ == "__main__":
    failures = main()
    print("\n" + "=" * 70)
    if not failures:
        print("RESULT: PASS — all steps completed without error.")
    else:
        print(f"RESULT: FAIL — {len(failures)} step(s) failed:")
        for label, exc in failures:
            print(f"  - {label}: {type(exc).__name__}: {exc}")
    print("=" * 70)
    sys.exit(1 if failures else 0)
